language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
deploy:
  providor: heroku
  api_key:
    secure: 1167531a-f8f8-4bc0-887b-b0456eb13500
  app: bcit-crs
  on:
    repo: Langelozzi/2911-group21
